# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

name: "update prerelease packages"

on:
  repository_dispatch:
    types: update-prerelease-packages
  schedule:
    - cron: "0 12 * * *" # everyday at noon

jobs:
  update-prerelease-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: search for updates
        shell: pwsh
        run: |
          & .\scripts\PrereleasePackageUpdater.ps1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update prerelease dependencies
          committer: Microsoft Graph DevX Tooling <GraphTooling@service.microsoft.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: prerelease-updates
          branch-suffix: timestamp
          delete-branch: true
          title: 'Updated prerelease dependencies'
          body: |
            This is an automated PR.
            Please review if only prerelease packages are updated to newer versions.
          labels: |
            prerelease update
          reviewers: |
            peombwa
            baywet
            MIchaelMainer
            nikithauc
            ddyett
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
