parameters:
  - name: 'shared'
    default: 'shared test'
    type: string

steps:
- task: PowerShell@2
  env:
    SHARED: ${{ parameters.shared }}

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $env:SHARED'

