parameters:
  - name: 'shared'
    default: 'shared test'
    type: string

variables:
  shared: $ {{ parameters.shared }}

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(shared)'