trigger: none
pr: none

parameters:
  - name: metadataVersion
    type: string
    default: 'beta'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $(metadataVersion)'