resources:
  repositories:
    - repository: microsoft-graph-docs
      type: github
      endpoint: microsoftgraph
      name: microsoftgraph/microsoft-graph-docs
      ref: master

parameters:
  - name: 'shared'
    default: 'shared test'
    type: string

steps:
- checkout: microsoft-graph-docs
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo $env:SHARED'
  env:
    SHARED: ${{ parameters.shared }}

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "second $env:SHARED"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo $(buildConfiguration)