# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

resources:
 repositories:
   - repository: docs
     type: github
     endpoint: zengin
     name: zengin/microsoft-graph-docs
     ref: master
   - repository: apidoctor
     type: github
     endpoint: zengin
     name: zengin/apidoctor
     ref: zengin/snippets
   - repository: dotnet
     type: github
     endpoint: zengin
     name: zengin/msgraph-sdk-dotnet
     ref: dev
   - repository: generator
     type: github
     endpoint: zengin
     name: zengin/MSGraph-SDK-Code-Generator
     ref: dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- checkout: docs
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: apidoctor
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: dotnet
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: generator
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: self
  clean: true
  fetchDepth: 1

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: MSGraph-SDK-Code-Generator/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Typewriter'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: apidoctor/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build ApiDoctor'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Raptor'