# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

resources:
 repositories:
   - repository: docs
     type: github
     endpoint: zengin
     name: zengin/microsoft-graph-docs
     ref: master
   - repository: apidoctor
     type: github
     endpoint: zengin
     name: zengin/apidoctor
     ref: zengin/snippets
   - repository: dotnet
     type: github
     endpoint: zengin
     name: zengin/msgraph-sdk-dotnet
     ref: dev
   - repository: metadata
     type: github
     endpoint: zengin
     name: zengin/msgraph-metadata
     ref: master
   - repository: generator
     type: github
     endpoint: zengin
     name: zengin/MSGraph-SDK-Code-Generator
     ref: master

variables:
  snippetInjectionPath: 'apidoctor'
  solution: '$(snippetInjectionPath)/**/*.sln'
  snippetApiUrl: 'https://graphexplorerapi.azurewebsites.net/api/GraphExplorerSnippets'
  snippetLanguages: 'C#'
  generatorPath: 'MSGraph-SDK-Code-Generator'
  typewriterSolution: '$(generatorPath)/**/Typewriter.sln'

pool:
  vmImage: 'windows-latest'

steps:
#- checkout: docs
#  clean: true
#  fetchDepth: 1
#  persistCredentials: true

- checkout: apidoctor
  clean: true
  fetchDepth: 1
  submodules: recursive
  persistCredentials: true

#- checkout: dotnet
#  clean: true
#  fetchDepth: 1
#  persistCredentials: true

- checkout: self
  clean: true
  fetchDepth: 1
  
- checkout: generator
  clean: true
  fetchDepth: 1
  submodules: recursive
  persistCredentials: true

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      $response = (Invoke-WebRequest api.github.com/repos/microsoftgraph/MSGraph-SDK-Code-Generator/releases).Content | ConvertFrom-Json
#      $typewriterUrl = $response[0].assets[0].browser_download_url
#
#      $zipLocation = Join-Path $(Agent.TempDirectory) "typewriter.zip"
#      Invoke-WebRequest $typewriterUrl -OutFile $zipLocation
#      Write-Host "downloaded to: ",(Resolve-Path $zipLocation).Path
#
#      # unzip
#      $unzipLocation = Join-Path $(Agent.TempDirectory) "unzipped"
#      mkdir $unzipLocation
#
#      Add-Type -AssemblyName System.IO.Compression.FileSystem
#      [System.IO.Compression.ZipFile]::ExtractToDirectory($zipLocation, $unzipLocation)
#      Write-Host "unzipped to: ",(Resolve-Path $unzipLocation).Path
#  continueOnError: true

- task: NuGetToolInstaller@1
  displayName: "Install Nuget.exe"

- task: NuGetCommand@2
  displayName: "Restore Packages for  Snippets Injection Tool"
  inputs:
    restoreSolution: '$(solution)'

- task: NuGetCommand@2
  displayName: "Restore Packages for  Typewriter"
  inputs:
    restoreSolution: '$(typewriterSolution)'

- task: VSBuild@1
  displayName: "Build Source for Typewriter"
  inputs:
    solution: '$(typewriterSolution)'
    platform: 'Any CPU'
    configuration: 'Release'

- task: VSBuild@1
  displayName: "Build Source for Snippets Injection Tool"
  inputs:
    solution: '$(solution)'
    platform: 'Any CPU'
    configuration: 'Release'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: msgraph-sdk-raptor/**/*.csproj
#    arguments: '--configuration $(buildConfiguration)'
#  displayName: 'Build Raptor'

#- task: CmdLine@2
#  displayName: "Run snippet injection against docs"
#  inputs:
#    script: |
#      cd $(graphDocsPath)
#      git config --global user.name "Eastman"
#      git config --global user.email "andrew.omondi@microsoft.com"
#      ..\\$(snippetInjectionPath)\\ApiDoctor.Console\\bin\\Release\\apidoc.exe generate-snippets --ignore-warnings --path . --snippet-api-url $(snippetApiUrl) --lang $(snippetLanguages) --github-token $(githubToken) --git-path "C:\Program Files\Git\bin\git.exe" --commit-message "Scheduled snippets update" --pull-request-title "Snippets Update"

