# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

variables:
  cond: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: A
    condition: eq(variables['cond'], true)
    steps:
      - pwsh: |
          Write-Host "Job A1"
        displayName: "Job A1"
      - pwsh: |
          Write-Host "Job A2"
        displayName: "Job A2"
  - job: B
    condition: succeeded('A')
    dependsOn:
      - A
    steps:
      - pwsh: |
          Write-Host "Job B1"
        displayName: "Job B1"
      - pwsh: |
          Write-Host "Job B2"
        displayName: "Job B2"
  - job: C
    dependsOn:
    - B
    steps:
      - pwsh: |
          Write-Host "Job C1"
        displayName: "Job C2"