# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: test
    type: step

jobs:
  - job: beta_metadata
    steps:
      - pwsh: |
          Write-Host "Create Beta Metadata"
        displayName: Create Beta Metadata
  - job: v1_metadata
    steps:
      - pwsh: |
          Write-Error "Create v1 Metadata"
        displayName: Create v1 Metadata
  - job: beta_generation
    dependsOn: beta_metadata
    condition: succeeded('beta_metadata')
    steps:
      - pwsh: |
          Write-Host "Generate Beta SDK"
        displayName: Generate Beta SDK
  - job: v1_generation
    dependsOn: v1_metadata
    condition: succeeded('v1_metadata')
    steps:
      - pwsh: |
          Write-Host "Generate V1 SDK"
        displayName: Generate V1 SDK