# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

resources:
 repositories:
   - repository: docs
     type: github
     endpoint: zengin
     name: zengin/microsoft-graph-docs
     ref: master
   - repository: apidoctor
     type: github
     endpoint: zengin
     name: zengin/apidoctor
     ref: zengin/snippets
   - repository: dotnet
     type: github
     endpoint: zengin
     name: zengin/msgraph-sdk-dotnet
     ref: dev
#   - repository: generator
#     type: github
#     endpoint: zengin
#     name: zengin/MSGraph-SDK-Code-Generator
#     ref: dev


pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- checkout: docs
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: apidoctor
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: dotnet
  clean: true
  fetchDepth: 1
  persistCredentials: true

- checkout: generator
  clean: true
  fetchDepth: 1
  persistCredentials: true
  submodules: recursive

- checkout: self
  clean: true
  fetchDepth: 1

#- task: MSBuild@1
#  inputs:
#    solution: '**/Typewriter.sln'
#  displayName: 'Build Typewriter'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $loc_download = $(Agent.TempDirectory)

      $response = (Invoke-WebRequest api.github.com/repos/microsoftgraph/MSGraph-SDK-Code-Generator/releases).Content | ConvertFrom-Json
      $typewriterUrl = $response[0].assets[0].browser_download_url

      $zipLocation = Join-Path $loc_download "typewriter.zip"
      Invoke-WebRequest $typewriterUrl -OutFile $zipLocation
      Write-Host "downloaded to: ",(Resolve-Path $zipLocation).Path

      # unzip
      $unzipLocation = Join-Path $loc_download "unzipped"
      mkdir $unzipLocation

      Add-Type -AssemblyName System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zipLocation, $unzipLocation)
      Write-Host "unzipped to: ",(Resolve-Path $unzipLocation).Path

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: apidoctor/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build ApiDoctor'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: msgraph-sdk-raptor/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Raptor'
