# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits

variables:
  cond: true

pool:
  vmImage: 'windows-latest'

jobs:
  - job: A
    condition: eq(variables['cond'], true)
    steps:
      - task: PowerShell@2
        displayName: "Job A1"
        inputs:
          targetType: 'inline'
          script: 'Write-Host "Job A1"'
      - task: PowerShell@2
        displayName: "Job A2"
        inputs:
          targetType: 'inline'
          script: 'Write-Host "Job A2"'
  - job: B
    condition: ne(variables['cond'], true)
    steps:
      - task: PowerShell@2
        displayName: "Job B1"
        inputs:
          targetType: 'inline'
          script: 'Write-Host "Job B1"'
      - task: PowerShell@2
        displayName: "Job A2"
        inputs:
          targetType: 'inline'
          script: 'Write-Host "Job B2"'
  - job: C
    dependsOn:
    - A
    - B
    steps:
      - task: PowerShell@2
        displayName: "Job C"
        inputs:
          targetType: 'inline'
          script: 'Write-Host "Job C"'
