variables:
  buildConfiguration: 'Release'
  typewriterSolution: 'MSGraph-SDK-Code-Generator/**/Typewriter.sln'
  apidoctorSolution: 'apidoctor/**/*.sln'
  snippetLanguages: 'C#' # possible values: 'C#,JavaScript,Objective-C,Java'
  runSettingsFile: '$(Build.SourcesDirectory)/msgraph-sdk-raptor/CSharpArbitraryDllTests/Test.runsettings'